In [1]:
counts = [
    [8, 6, 2, 1, 5, 0, 0, 1], 
    [0, 1, 4, 0, 1, 1, 0, 1], 
    [0, 1, 0, 7, 1, 0, 5, 2], 
    [0, 0, 2, 0, 1, 7, 3, 4]
]

In [2]:
import numpy as np

In [5]:
counts = np.array(counts)

In [6]:
f = counts/8

In [7]:
f

array([[1.   , 0.75 , 0.25 , 0.125, 0.625, 0.   , 0.   , 0.125],
       [0.   , 0.125, 0.5  , 0.   , 0.125, 0.125, 0.   , 0.125],
       [0.   , 0.125, 0.   , 0.875, 0.125, 0.   , 0.625, 0.25 ],
       [0.   , 0.   , 0.25 , 0.   , 0.125, 0.875, 0.375, 0.5  ]])

In [9]:
pwm = np.log2(f/0.25)

/Users/wassilyminkow/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log2
  """Entry point for launching an IPython kernel.


In [10]:
pwm

array([[ 2.        ,  1.5849625 ,  0.        , -1.        ,  1.32192809,
               -inf,        -inf, -1.        ],
       [       -inf, -1.        ,  1.        ,        -inf, -1.        ,
        -1.        ,        -inf, -1.        ],
       [       -inf, -1.        ,        -inf,  1.80735492, -1.        ,
               -inf,  1.32192809,  0.        ],
       [       -inf,        -inf,  0.        ,        -inf, -1.        ,
         1.80735492,  0.5849625 ,  1.        ]])

In [11]:
i_pwn = np.multiply(f, pwm)

/Users/wassilyminkow/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in multiply
  """Entry point for launching an IPython kernel.


In [28]:
i_pwn

array([[ 2.        ,  1.18872188,  0.        , -0.125     ,  0.82620506,
         0.        ,  0.        , -0.125     ],
       [ 0.        , -0.125     ,  0.5       ,  0.        , -0.125     ,
        -0.125     ,  0.        , -0.125     ],
       [ 0.        , -0.125     ,  0.        ,  1.58143556, -0.125     ,
         0.        ,  0.82620506,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        , -0.125     ,
         1.58143556,  0.21936094,  0.5       ]])

In [18]:
where_are_NaNs = np.isnan(i_pwn)
i_pwn[where_are_NaNs] = 0

In [21]:
sum(sum(i_pwn))

8.098364045521311

In [22]:
counts_x = counts + 1 

In [23]:
f_x = counts_x/12

In [25]:
f_x

array([[0.75      , 0.58333333, 0.25      , 0.16666667, 0.5       ,
        0.08333333, 0.08333333, 0.16666667],
       [0.08333333, 0.16666667, 0.41666667, 0.08333333, 0.16666667,
        0.16666667, 0.08333333, 0.16666667],
       [0.08333333, 0.16666667, 0.08333333, 0.66666667, 0.16666667,
        0.08333333, 0.5       , 0.25      ],
       [0.08333333, 0.08333333, 0.25      , 0.08333333, 0.16666667,
        0.66666667, 0.33333333, 0.41666667]])

In [26]:
pwm_x = np.log2(f_x/0.25)

In [27]:
pwm_x

array([[ 1.5849625 ,  1.22239242,  0.        , -0.5849625 ,  1.        ,
        -1.5849625 , -1.5849625 , -0.5849625 ],
       [-1.5849625 , -0.5849625 ,  0.73696559, -1.5849625 , -0.5849625 ,
        -0.5849625 , -1.5849625 , -0.5849625 ],
       [-1.5849625 , -0.5849625 , -1.5849625 ,  1.4150375 , -0.5849625 ,
        -1.5849625 ,  1.        ,  0.        ],
       [-1.5849625 , -1.5849625 ,  0.        , -1.5849625 , -0.5849625 ,
         1.4150375 ,  0.4150375 ,  0.73696559]])

In [33]:
i_pwm_x = np.multiply(f_x, pwm_x)

In [34]:
i_pwm_x

array([[ 1.18872188,  0.71306225,  0.        , -0.09749375,  0.5       ,
        -0.13208021, -0.13208021, -0.09749375],
       [-0.13208021, -0.09749375,  0.307069  , -0.13208021, -0.09749375,
        -0.09749375, -0.13208021, -0.09749375],
       [-0.13208021, -0.09749375, -0.13208021,  0.94335833, -0.09749375,
        -0.13208021,  0.5       ,  0.        ],
       [-0.13208021, -0.13208021,  0.        , -0.13208021, -0.09749375,
         0.94335833,  0.13834583,  0.307069  ]])

In [35]:
sum(sum(i_pwm_x))

3.210658571847579